package shared.protocol.persistence;

public interface Code extends HeaderElement {
    enum RequestCode implements Code {
        LOGIN, LOGOUT, REFRESH_SESSION,//AUTH
        GET_USER_INFO,//USER
        GET_SELECTION_SCHEDULE, GET_MEAL_PLAN, GET_DORMITORY_ROOMS,GET_DORMITORY_ROOM_TYPE, SELECT_PRIORITY_APPLICATION, APPLY_ROOMMATE, APPLY_MEAL, APPLY_ROOM,
        MOVE_OUT, GET_SELECTION_RESULT, GET_MERIT_AND_DEMERIT_POINTS, UPLOAD_TUBER_REPORT, GET_FILE_FOR_PROOF,
        UPLOAD_FILE_FOR_PROOF, APPLICATION,//STUDENT
        REGISTER_SELECTION_INFO, GET_APPLICANTS, SELECT_APPLICANTS, MANAGEMENT_MERIT_POINT, CONFIRM_TUBER_REPORT, GET_MOVE_OUT_APPLICANTS,
        CONFIRM_FILE_PROOF, APPROVE_MOVE_OUT, //ADMIN
        GET_PAYMENT_AMOUNT, GET_PAYMENT_STATUS,BANK_TRANSFER, CARD_MOVEMENT, REFUND_REQUEST,
        //REFUND_CONFIRM,
        GET_REFUND_STATEMENT//PAYMENT
        // 내가 임의로 추가
        , CHECK_MOVE_OUT, BILL, GET_RECEIPT, GET_PAYMENT_CHECK

    }

    enum ResponseCode implements Code {
        OK,
    }

    enum ErrorCode implements Code {
        INTERNAL_SERVER_ERROR,
        INVALID_VALUE,
        INVALID_TYPE,
        INVALID_CODE,
        INVALID_PROTOCOL,
        UNAUTHORIZED,
        INVALID_REQUEST
    }

    enum ValueCode implements Code {
        ID, PASSWORD,USER_NAME,PHONE_NUMBER,GENDER_NAME,DO,SI,DETAIL_ADDRESS, SESSION_ID,SELECTION_INFO,
        SELECTION_STATUS,SUM_OF_MERIT_POINTS,PRICE,PROOF_FILE, PREFERENCE,USER_TYPE,
        TUBER_REPORT,PAYMENT_STATUS_NAME,PAYMENT_AMOUNT, ACCOUNT_NUMBER, ACCOUNT_HOLDER_NAME,BANK_NAME,CARE_NUMBER,CARD_ISSUER,
        REFUND_STATUS,REFUND_AMOUNT, CARD_CODE, BANK_CODE, REFUND_REASON,
        PRIORITY,MEAL_PLAN, MEAL_TYPE, MOVE_OUT_STATUS
        ,DORMITORY_ROOM_TYPE, MOVE_OUT_REQUEST, SELECTION_SCHEDULE, DEMERIT_POINT, MESSAGE
        ,DEMERIT_REASON, BED_NUMBER, ROOM_NUMBER

        ,SNORE//코골이 불리언
        ,ONEYEAR_LASTING //일년호실 불리언
    }
}
