package server.network.protocol.TLV;

public interface Code {
    enum RequestOperation  {
        LOGIN, LOGOUT, REFRESH_SESSION,//AUTH
        GET_USER_INFO,//USER
        GET_SELECTION_SELECTION, GET_MEAL_PLAN, GET_DORMITORY_ROOM_TYPE, SELECT_PRIORITY_APPLICATION, APPLY_ROOMMATE, APPLY_MEAL, APPLY_ROOM,
        MOVE_OUT, GET_SELECTION_RESULT, GET_MERIT_AND_DEMERIT_POINTS, UPLOAD_TUBER_REPORT, GET_BILL, GET_FILE_FOR_PROOF_UPLOAD_FILE_FOR_PROOF,//STUDENT
        REGISTER_SELECTION_INFO, GET_APPLICANTS, SELECT_APPLICANTS, MANAGEMENT_MERIT_POINT, CONFIRM_TUBER_REPORT, GET_MOVE_OUT_APPLICANTS,
        CONFIRM_FILE_PROOF, APPROVE_MOVE_OUT, //ADMIN
        GET_PAYMENT, BANK_TRANSFER, CARD_MOVEMENT, REFUND_REQUEST, REFUND_CONFIRM, GET_REFUND_STATEMENT//PAYMENT
    }
    enum RequestValue {
        ID, PASSWORD, SESSION_ID,USER_INFO,SELECTION_INFO,
        SELECTION_STATUS,SUM_OF_MERIT_POINTS,PRICE,PROOF_FILE,USER_ID,
        TUBER_REPORT,PAYMENT_STATUS_NAME,PAYMENT_AMOUNT
    }

    enum Response {
        SUCCESS,
        ID, PASSWORD, SESSION_ID,USER_INFO,SELECTION_INFO, SELECTION_SCHEDULE,
        SELECTION_STATUS,SUM_OF_MERIT_POINTS,PRICE,PROOF_FILE,USER_ID,
        TUBER_REPORT,PAYMENT_STATUS_NAME,PAYMENT_AMOUNT
    }

    enum Error {
        INTERNAL_SERVER_ERROR,
        INVALID_VALUE,
        INVALID_TYPE,
        INVALID_CODE,
        INVALID_PROTOCOL,
        UNAUTHORIZED,
    }
}
